# This is a basic workflow to help you get started with Actions

name: aptall Syntax Check

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the nightly branch
  push:
    branches: [ nightly ]
    paths:
      - '**.sh'
  pull_request:
    branches: [ nightly ]
    paths:
      - '**.sh'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  Ubuntu:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        env:
          IS_DEBUG: TRUE

      # Runs a single command using the runners shell
      - name: Initialize aptall
        run: $GITHUB_WORKSPACE/aptall.sh
        
      # Runs a set of commands using the runners shell
      - name: Run aptall to test the elapsed time
        run: $GITHUB_WORKSPACE/aptall.sh
      - name: Print aptall runtime
        run: $GITHUB_WORKSPACE/aptall.sh runtime
      - name: Print aptall version
        run: $GITHUB_WORKSPACE/aptall.sh version
      - name: Print aptall changelog
        run: $GITHUB_WORKSPACE/aptall.sh changelog
      - name: aptall config files delete
        run: $GITHUB_WORKSPACE/aptall.sh remove
